## What is Numpy? <br/>
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.<br/>
## Why Numpy over Lists?
<ul>
<li>Requires Less Memory</li>
<li>Fast</li>
<li>Convinient</li>    
</ul>
<br/>
<b>Let's check all one by one</b>

In [4]:
# Requires Less MEMORY SPACE

import numpy as np
import sys

l=range(1000) # Creating list with lenth=1000
print("List requires " + str(sys.getsizeof(5)*len(l)) + " bytes of memory") #It will print the total memory in bytes required by the list, as sys.getsizeof(int) will give the memory acquired by one integer in the system, and then it is multiplied by 1000 to predict the memory alloted for the list

array=np.arange(1000)
print("Array requires " + str(array.size*array.itemsize) + " bytes of memory")

List requires 14000 bytes of memory
Array requires 4000 bytes of memory


As clearly visible from the above code numpy array requires less memory as compare to python list, the reason for this is in Numpy array 1 int elements requires 4 bytes of memory space while in case of python lists 1 element requires 14 bytes of memory space(because the lists here contains the list of pointers first and then each pointer points to another location in the memory thus requires large memory)

In [7]:
# Requires Less TIME

import time

# I have created two lists for size 100000
l1= range(100000)
l2= range(100000)

arr1=np.arange(100000)
arr2=np.arange(100000)

start = time.time()
result = [x+y for x,y in zip(l1,l2)]
    
print("Total time taken by python list: " + str((time.time() - start)*1000)) # Difference between the start 

start = time.time()
result = arr1+arr2
print("Total time taken by numpy array: " + str((time.time() - start)*1000))


Total time taken by python list: 37.89663314819336
Total time taken by numpy array: 1.0063648223876953


As clearly visible fromt the above results that the time taken by the Numpy array is very less as compare to the time taken by the the Python list for performing the same task.<br/><br/>
<b>Convinient</b><br/>
As shown above it is very easy to perform operation on the numpy array as compare to python list,
like refer the example as shown below


In [12]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

# Difference between the above two arrays can be calculated simply by subtracting the two arrays

result = ar2 - ar1
print("Array result: "+ str(result))

# but in case of Pyhton list it is quite difficult like

l1=[1,2,3]
l2=[4,5,6]
result = [y-x for x,y in zip(l1,l2)]
print("Python list result: "+ str(result))    


Array result: [3 3 3]
Python list result: [3, 3, 3]


<B>Single-Dimentional Array creation using Numpy</B>

In [26]:
arr= np.array([1,2,3,4,5])

#Extracting particular value
print("Value at first index: " + str(arr[1])) # Because the array starts from 0 index 

#Prints the Dimensions of an array
print("Dimensions of an array: " + str(arr.ndim)) 

#Print itemsize(Memory space required by an item)
print("Memory space requires by an integer: " + str(arr.itemsize))

#Print the datatype of the elements in an array
print("Datatype of the elements is: " + str(arr.dtype))

Value at first index: 2
Dimensions of an array: 1
Memory space requires by an integer: 4
Datatype of the elements is: int32


<b>Multi-dimensional Array using Numpy</b>

In [34]:
arr = np.array([[1,2],[3,4],[4,5],[6,7]])
print("Array with datatype as integer"+ str(arr))
# Creating an array with float datatype
arr1=np.array([[1,2], [3,4], [5,6]], dtype=np.float64 )
print("Array with datatype as float"+ str(arr1))

#Print the size(number of elements) of the array
print("Size is: "+ str(arr.size))

#Print the shape(dimensions) on the array
print("Dimensions ar: e" + str(arr.shape))

Array with datatype as integer[[1 2]
 [3 4]
 [4 5]
 [6 7]]
Array with datatype as float[[1. 2.]
 [3. 4.]
 [5. 6.]]
Size is: 8
Dimensions are(4, 2)


<B>Initializing values in array</B> 

In [37]:
array = np.zeros((3,4))
print("Array with all values as zeros" + str(array))

array1 = np.ones((3,4))
print("Array with all values as ones" + str(array1))

Array with all values as zeros[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array with all values as ones[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<b>Arange function in Numpy</b>

In [38]:
array2 = np.arange(1,5)
print("Print an array with elements 1,2,3,4" + str(array2))

array3 = np.arange(1,5,2)
print("Print an array with elements 1,3 here it will take a step of 2 in range 1 to 5(don't include 5): " + str(array3))

Print an array with elements 1,2,3,4[1 2 3 4]
Print an array with elements 1,3 here it will take a step of 2 in range 1 to 5(don't include 5)[1 3]


<b>How to change the dimensions of an numpy array</b>

In [43]:
print("Array with shape(3,4): " + str(array))

array4=array.reshape(4,3)
print("Same array with new dimensions as(4,3):" + str(array4))

Array with shape(3,4): [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Same array with new dimensions as(4,3):[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<b>Other Basics Mathematical operations on Array: </b>

In [56]:
array5=np.array([[1,2,3],[4,5,6],[7,8,9]])

#Print the maximum element of the array
print("Maximum element is: " + str(array5.max()))

#Print the minimum element of the array
print("Minimum element is: " + str(array5.min()))

#Print the sum of all the elements of the array
print("Sum of all elements is: " + str(array5.sum()))

#Print the square root of all the elements of the array
print("Square root of all elements is: " + str(np.sqrt(array5)))

array6=np.array([[11,21,13],[4,15,8],[2,1,17]])

#Print the sum of two arrays
print("Sum of two arrays is: " + str(array5 + array6))

#Print the difference of two arrays
print("Difference of two arrays is: " + str(array5 - array6))

#Print the product of two arrays
print("Product of two arrays is: " + str(array5 * array6))

#Print the product of two arrays(Matrix multiplication)
print("Matrix multiplication of two arrays is: " + str(array5.dot(array6)))

Maximum element is: 9
Minimum element is: 1
Sum of all elements is: 45
Square root of all elements is: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
Sum of two arrays is: [[12 23 16]
 [ 8 20 14]
 [ 9  9 26]]
Difference of two arrays is: [[-10 -19 -10]
 [  0 -10  -2]
 [  5   7  -8]]
Product of two arrays is: [[ 11  42  39]
 [ 16  75  48]
 [ 14   8 153]]
Matrix multiplication of two arrays is: [[ 25  54  80]
 [ 76 165 194]
 [127 276 308]]


<b>Indexing and Slicing</b>

In [62]:
array7 = np.array([1,2,4,5])

#print first two elements of the array
print("Frist two elements are: "+ str(array7[0:2]))

#print last two elements of the array
print("Last two elements are: "+ str(array7[2:4]))

#To get a particular element of an Multi Dimensional Array
array8 = np.array([[1,2,3], [4,5,6], [7,8,9]])

#To get element at 2nd row and 1st column, here as the index in array starts from 0 hence our desired element will be available at the index (1,0)
print("Element at second row and first column is: " + str(array8[1,0]))

# To get elements of first two rows and second column
print("Elements of first two rows and second column are: " + str(array8[0:2,1]) )

Frist two elements are: [1 2]
Last two elements are: [4 5]
Element at second row and first column is: 4
Elements of first two rows and second column are: [2 5]


<b>Stacking of one array over ather</b>

In [70]:
print(np.vstack((array5, array6))) # It will vertically stack array5 over array6

print(np.hstack((array5, array6))) # It will horizontally stack array5 over array6



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 21 13]
 [ 4 15  8]
 [ 2  1 17]]
[[ 1  2  3 11 21 13]
 [ 4  5  6  4 15  8]
 [ 7  8  9  2  1 17]]


<b>Splitting of the array</b>

In [76]:
#To split the array in 3 equal parts
array9 = np.arange(18).reshape(3,6) # Make an array with a total of 18 elements and having dimensions 3 * 6
print("Newly created array is: " + str(array9))

result = np.hsplit(array9,3) #Split the array in 3 equal parts
print(result[0])
print(result[1])
print(result[2])

#Similarly we can perform vrtical split

Newly created array is: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1]
 [ 6  7]
 [12 13]]
[[ 2  3]
 [ 8  9]
 [14 15]]
[[ 4  5]
 [10 11]
 [16 17]]


<b> Getting boolean values</b>

In [80]:
b = array9 > 5
print(b) # Print True if element is greater than 5 and false if element is less than 5 

array10 = array9[b] # Give all the value for which b is True
print(array10)


[[False False False False False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


<b>Iterating through each element in numpy array</b>

In [87]:
array11 = np.arange(9,18).reshape(3,3)
print("Array is: " + str(array11))

for i in range(3):
    for j in range(3):
        print(array11[i][j])
# Performing the same above task using array.flatten function       
print("Performing it using array.flatten")
for i in array11.flatten():
    print(i)

Array is: [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
9
10
11
12
13
14
15
16
17
Performing it using array.flatten
9
10
11
12
13
14
15
16
17


<b>If you want to know more about it go and visit Numpy official documentation</b><br/><br/>
Signing off for this tutorial<br/>
Happy coding
